build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
        - MINGW_CONFIGURATIONS: '4.9@x86@dwarf2@posix,5@x86@dwarf2@posix,6@x86@dwarf2@posix,7@x86@dwarf2@posix,8@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '4.9@x86_64@seh@posix,5@x86_64@seh@posix,6@x86_64@seh@posix,7@x86_64@seh@posix,8@x86_64@seh@posix'

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          ARCH: x86
          CONAN_ARCHS: x86
          CPT_TEST_FOLDER: test_package_installer
          CONAN_CONANFILE: conanfile_installer.py

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          ARCH: x86_64
          CONAN_ARCHS: x86_64
          CPT_TEST_FOLDER: test_package_installer
          CONAN_CONANFILE: conanfile_installer.py


install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
